import { StyleSheet } from 'react-native';
import { theme } from '../../constants/nestledger';

// Extracted from NestLedgerApp.tsx (2026-08-05) — static style sheet.
export const styles = StyleSheet.create({
  amountText: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '700',
  },
  analyseCardRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  analyseCardIcon: {
    alignItems: 'center',
    backgroundColor: theme.primarySoft,
    borderRadius: 12,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  analyseCardTitle: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 2,
  },
  appShell: {
    backgroundColor: theme.background,
    flex: 1,
    paddingHorizontal: 20,
  },
  authCard: {
    gap: 14,
  },
  authWrap: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
  },
  backRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    marginBottom: 2,
  },
  backRowText: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  spaceTypeGrid: {
    gap: 10,
  },
  spaceTypeCard: {
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 2,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  spaceTypeCardActive: {
    backgroundColor: theme.primarySoft,
    borderColor: theme.primary,
  },
  spaceTypeEmoji: {
    fontSize: 22,
    marginBottom: 4,
  },
  spaceTypeLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '700',
  },
  spaceTypeLabelActive: {
    color: theme.primary,
  },
  spaceTypeDesc: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  spaceTypeDescActive: {
    color: theme.primary,
  },
  breakdownSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  breakdownStat: {
    alignItems: 'center',
    flex: 1,
    gap: 2,
  },
  breakdownStatValue: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '700',
  },
  breakdownStatLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  detailsToggle: {
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 4,
  },
  detailsToggleText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  cycleStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cycleStat: {
    flex: 1,
    gap: 2,
  },
  cycleStatValue: {
    color: theme.text,
    fontSize: 22,
    fontWeight: '700',
  },
  cycleStatLabel: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: '500',
  },
  cycleStatDivider: {
    width: 1,
    height: 36,
    backgroundColor: theme.border,
    marginHorizontal: 16,
  },
  borrowStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  borrowStatItem: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
  },
  borrowStatValue: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '700',
  },
  borrowStatLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  avatarChoice: {
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  avatarChoiceActive: {
    backgroundColor: theme.primarySoft,
    borderColor: theme.primary,
  },
  avatarChoiceText: {
    fontSize: 24,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  currencyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  currencyChip: {
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  currencyChipActive: {
    backgroundColor: theme.primarySoft,
    borderColor: theme.primary,
  },
  currencyChipCode: {
    color: theme.text,
    fontSize: 13,
    fontWeight: '600',
  },
  currencyChipCodeActive: {
    color: theme.primary,
  },
  currencyChipSymbol: {
    color: theme.textMuted,
    fontSize: 12,
  },
  currencyChipSymbolActive: {
    color: theme.primary,
  },
  badge: {
    alignItems: 'center',
    backgroundColor: theme.secondary,
    borderRadius: 999,
    height: 18,
    justifyContent: 'center',
    minWidth: 18,
    paddingHorizontal: 4,
    position: 'absolute',
    right: -8,
    top: -6,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },
  bellButton: {
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 20,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  bentoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  bodyMuted: {
    color: theme.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  bottomTabs: {
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 26,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  cardEyebrow: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  cardTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: '700',
  },
  centerCard: {
    alignItems: 'center',
    gap: 12,
    width: '100%',
  },
  centerWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  contentWrap: {
    gap: 18,
    paddingBottom: 40,
  },
  dualActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  emptyWrap: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 26,
  },
  errorText: {
    color: theme.danger,
    fontSize: 14,
    fontWeight: '600',
  },
  footnote: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  headerBlock: {
    gap: 14,
  },
  headerContent: {
    flex: 1,
    gap: 4,
  },
  heroTitle: {
    color: theme.text,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
  },
  infoPill: {
    backgroundColor: theme.surfaceMuted,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  infoPillLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  infoPillValue: {
    color: theme.text,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  inlineBanner: {
    alignItems: 'center',
    backgroundColor: theme.secondarySoft,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    padding: 14,
  },
  inlineBannerText: {
    color: theme.text,
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  input: {
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    color: theme.text,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  textInput: {
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 12,
    borderWidth: 1,
    color: theme.text,
    fontSize: 15,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  itemInputRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    alignItems: 'center',
  },
  itemNameInput: {
    flex: 1,
  },
  itemPriceInput: {
    width: 100,
  },
  removeItemButton: {
    padding: 4,
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
  },
  addItemText: {
    color: theme.primary,
    fontSize: 15,
    fontWeight: '600',
  },
  totalText: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '700',
  },
  suggestionHint: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  suggestionList: {
    gap: 8,
    marginTop: 10,
  },
  suggestionButton: {
    alignItems: 'center',
    backgroundColor: theme.surfaceMuted,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  suggestionContent: {
    flex: 1,
    gap: 2,
  },
  suggestionTitle: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '700',
  },
  suggestionMeta: {
    color: theme.textMuted,
    fontSize: 12,
  },
  suggestionAmount: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  expenseCardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  expenseDetails: {
    flex: 1,
    marginRight: 12,
  },
  expenseActions: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },
  totalAmount: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  expenseDescription: {
    color: theme.textMuted,
    fontSize: 14,
    fontStyle: 'italic',
    marginBottom: 4,
  },
  itemsList: {
    marginBottom: 8,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
  },
  itemName: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
    marginRight: 8,
  },
  itemPrice: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '500',
  },
  inputGroup: {
    gap: 10,
  },
  fieldSection: {
    gap: 12,
    marginTop: 8,
  },
  inputLabel: {
    color: theme.text,
    fontSize: 14,
    fontWeight: '700',
  },
  dateButton: {
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dateButtonText: {
    color: theme.text,
    fontSize: 16,
  },
  kicker: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  linkBlock: {
    color: theme.text,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
  },
  linkText: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  listRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 10,
  },
  listSubtitle: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  listTitle: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '700',
  },
  loaderWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  memberAvatar: {
    alignItems: 'center',
    backgroundColor: theme.primarySoft,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    marginRight: 12,
    width: 48,
  },
  memberAvatarText: {
    fontSize: 22,
  },
  metricText: {
    color: theme.text,
    fontSize: 28,
    fontWeight: '800',
    marginTop: 4,
  },
  modalContent: {
    gap: 14,
    padding: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    alignItems: 'center',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  modalScreen: {
    backgroundColor: theme.background,
    flex: 1,
  },
  modalTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '700',
  },
  confirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmCard: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    padding: 24,
    width: '85%',
    maxWidth: 360,
    alignItems: 'center',
  },
  confirmIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.dangerSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  confirmTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  confirmBody: {
    color: theme.textMuted,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 24,
    textAlign: 'center',
  },
  confirmButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  confirmCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: theme.surfaceMuted,
    alignItems: 'center',
  },
  confirmCancelText: {
    color: theme.textMuted,
    fontSize: 16,
    fontWeight: '700',
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: theme.primary,
    alignItems: 'center',
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  confirmDestructive: {
    backgroundColor: theme.danger,
  },
  confirmDestructiveText: {
    color: '#fff',
  },
  planCard: {
    gap: 14,
  },
  profileSwitcherButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  quickActionCard: {
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: 8,
    minHeight: 112,
    justifyContent: 'center',
    width: '48%',
  },
  quickActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  quickActionText: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '700',
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowGap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  iconRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  rowEnd: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  reminderSection: {
    marginTop: 16,
    marginBottom: 16,
    gap: 12,
  },
  reminderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  reminderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  reminderTextWrap: {
    flex: 1,
  },
  reminderText: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '600',
  },
  reminderSubtext: {
    color: theme.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  toggleButton: {
    width: 52,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.border,
    padding: 2,
    justifyContent: 'center',
  },
  toggleButtonActive: {
    backgroundColor: theme.primary,
  },
  toggleCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
  },
  toggleCircleActive: {
    alignSelf: 'flex-end',
  },
  timePickerRow: {
    gap: 8,
  },
  timeInput: {
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 12,
    borderWidth: 1,
    color: theme.text,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  timeHint: {
    color: theme.textMuted,
    fontSize: 12,
    fontStyle: 'italic',
  },
  editButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 36,
    padding: 4,
  },
  screen: {
    backgroundColor: theme.background,
    flex: 1,
  },
  sectionGap: {
    gap: 16,
  },
  sectionTitle: {
    color: theme.text,
    fontSize: 22,
    fontWeight: '800',
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  monthSelectorWrap: {
    marginBottom: 12,
  },
  yearNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginVertical: 6,
  },
  yearNavArrow: {
    padding: 6,
  },
  yearNavArrowDisabled: {
    opacity: 0.3,
  },
  yearNavText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    minWidth: 48,
    textAlign: 'center',
  },
  monthScrollRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  archiveBadge: {
    backgroundColor: theme.primarySoft,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 12,
  },
  archiveBadgeText: {
    fontSize: 12,
    color: theme.primary,
    fontWeight: '500',
  },
  sheetBackdrop: {
    backgroundColor: 'rgba(45, 49, 47, 0.32)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetCard: {
    backgroundColor: theme.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  sheetContent: {
    gap: 16,
    paddingBottom: 32,
  },
  sheetGrabber: {
    alignSelf: 'center',
    backgroundColor: theme.border,
    borderRadius: 999,
    height: 5,
    marginBottom: 14,
    width: 44,
  },
  shoppingCard: {
    gap: 12,
  },
  deleteAction: {
    backgroundColor: theme.danger,
    justifyContent: 'center',
    alignItems: 'center',
    width: 80,
    borderRadius: 16,
    marginVertical: 4,
  },
  deleteButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  spacer12: {
    height: 12,
  },
  spacer16: {
    height: 16,
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginVertical: 14,
  },
  strikethrough: {
    textDecorationLine: 'line-through',
  },
  borrowRecordRow: {
    borderTopColor: theme.border,
    borderTopWidth: 1,
    marginTop: 6,
    paddingTop: 6,
  },
  borrowHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  switcherCard: {
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 18,
  },
  switcherEmoji: {
    fontSize: 24,
  },
  switcherHeader: {
    gap: 8,
  },
  switcherWrap: {
    gap: 16,
    padding: 20,
  },
  tabBadge: {
    right: -10,
    top: -8,
  },
  tabButton: {
    alignItems: 'center',
    gap: 6,
    minWidth: 64,
  },
  tabLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  tabLabelActive: {
    color: theme.primary,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    marginTop: 8,
  },
  topBarSubtitle: {
    color: theme.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  topBarTitle: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '700',
  },
});
